export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  GET_CATEGORIES: "GET_CATEGORIES",
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  GET_PRODUCTS_BY_CATEGORIES: "GET_PRODUCTS_BY_CATEGORIES",
};
